---
notifications:
  email:
    on_success: never
    on_failure: change

language: python
python:
  - '2.7'

install:
  - pip install tox-travis coveralls
  - python setup.py install

script:
  - tox

# TODO: enable once a module is added
# after_script:
#   - coveralls
