---
notifications:
  email:
    on_success: never
    on_failure: change

language: python
python:
  - '2.7'

install:
  - pip install tox-travis coveralls
  - python setup.py install

script:
  - tox

after_script:
  - coveralls
